services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017

  backend:
    build:
      context: backend
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - database

  frontend:
    build:
      context: frontend
      target: dev
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - database
      - backend