services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: polynotes
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    networks:
      - private

  backend:
    build:
      context: backend
      target: prod
    restart: always
    volumes:
      - ./backend/src:/app/src:ro
    ports:
      - 5000:5000
    networks:
      - private
    depends_on:
      - mongo

  # frontend:
  #   build:
  #     context: frontend
  #     target: dev
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./frontend/src:/app/src:ro

networks:
  private:
    driver: bridge

volumes:
  data:
