apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  name: app-polynotes-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
  - host: cluster-2022-9.dopolytech.fr
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.appName }}
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.tls.host }}
    secretName: {{ .Values.tls.host }}
status:
  loadBalancer:
    ingress:
    {{ toYaml .Values.ingress | indent 4 }}

