#
name: polynotes-backend
namespace: sylvain

replicaCount: 1

image:
  repository: sylvainpierrot/polynotes-backend
  pullPolicy: Always
  tag: 835466f
    
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
- name: MAILER_HOST
  value: "smtp.etu.umontpellier.fr"
- name: MAILER_PORT
  value: "587"
- name: MAILER_USER
  value: "sylvain.pierrot@etu.umontpellier.fr"
- name: EXPIRESIN
  value: "5h"
- name: BASE_URL
  value: "http://localhost:5000"
- name: MONGODB_URL
  valueFrom:
    secretKeyRef:
      name: polynotes-sylvain-pwd
      key: mongodb-url
- name: MAILER_PASSWORD
  valueFrom:
    secretKeyRef:
      name: polynotes-sylvain-pwd
      key: mailer-password
- name: SECRETKEY
  valueFrom:
    secretKeyRef:
      name: polynotes-sylvain-pwd
      key: secret-key