#
name: polynotes-backend
namespace: sylvain

replicaCount: 1

image:
  repository: sylvainpierrot/polynotes-backend
  pullPolicy: Always
  tag: c715ae3
    
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi