#
name: polynotes-frontend
namespace: sylvain

replicaCount: 1

image:
  repository: sylvainpierrot/polynotes-frontend
  pullPolicy: Always
  tag: b7436fb
    
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi