#
name: polynotes-frontend
namespace: sylvain

replicaCount: 1

image:
  repository: sylvainpierrot/polynotes-frontend
  pullPolicy: Always
  tag: "8450350"
    
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
- name: REACT_APP_BASE_URL
  value: "https://polynotes.cluster-2022-9.dopolytech.fr/api"
