apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: sylvain
spec:
  replicas: {{ .Values.frontend.replica | default 1}}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}/{{ .Values.frontend.image.name}}:{{ .Values.frontend.image.tag}}"
        ports:
        - containerPort: 80
  