apiVersion: v1
kind: Service
metadata:
  name: svc-frontend
  namespace: sylvain
  labels:
    app: svc-frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: frontend
