apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-polynotes
  name: frontend-polynotes
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend-polynotes
  type: ClusterIP