apiVersion: v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80metadata:
  name: polynotes-service
spec:
  selector:
    app.kubernetes.io/name: polynotes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80