apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-polynotes
  namespace: sylvain
  labels:
    app: polynotes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: polynotes
  template:
    metadata:
      labels:
        app: polynotes
    spec:
      containers:
      - name: polynotes
        image: sylvainpierrot/polynotes-frontend:3bc2cb2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-polynotes
  namespace: sylvain
spec:
  selector:
    app: polynotes
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 80