name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-push-images:
    name: Build and publish image Frontend
    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: frontend
          target: runner
          push: true
          tags: sylvainpierrot/polynotes-frontend:${{ steps.commit.outputs.short }}

      - name: Update Version
        run: |
          git_hash=${{ steps.commit.outputs.short }}
          version=$(cat charts/polynotes-chart/templates/polynotes.yaml | grep image: | awk '{print $2}')
          sed -i "s|$version|sylvainpierrot/polynotes-frontend:${git_hash}|" charts/polynotes-chart/templates/polynotes.yaml
          
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Update image chart helm