name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-push-images:
    name: Build and publish Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: frontend
          target: dev
          push: true
          tags: sylvainpierrot/polynotes-frontend:latest

  deploy-k8s:
    name: Deploy on cluster Polytech
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Install Wireguard
      #   run: sudo apt install wireguard

      - name: Set up WireGuard
        uses: egor-tensin/setup-wireguard@v1.2.0
        with:
          endpoint: '${{ secrets.ENDPOINT }}'
          endpoint_public_key: '${{ secrets.ENDPOINT_PUBLIC }}'
          ips: '${{ secrets.IPS }}'
          allowed_ips: '${{ secrets.ALLOWED_IPS }}'
          private_key: '${{ secrets.PRIVATE }}'
          keepalive: '${{ secrets.KEEPALIVE }}'

      # - name: Deploy
      #   uses: WyriHaximus/github-action-helm3@v2
      #   with:
      #     exec: helm upgrade polynotes ./helm --install --wait --atomic --namespace=sylvain --values=./helm/values.yaml
      #     kubeconfig: '${{ secrets.KUBECONFIG }}'